# Generated by Django 3.0 on 2019-12-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0003_auto_20191215_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default='4545', on_delete=django.db.models.deletion.CASCADE, to='hey.Location'),
        ),
    ]
