# Generated by Django 3.0 on 2019-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0004_auto_20191215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
