# Generated by Django 3.0 on 2019-12-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0008_auto_20191215_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
    ]
