# Generated by Django 3.0 on 2019-12-16 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0009_remove_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category_item',
            field=models.ForeignKey(default=datetime.datetime(2019, 12, 16, 7, 52, 3, 473485, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='hey.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='location_item',
            field=models.ForeignKey(default=datetime.datetime(2019, 12, 16, 7, 52, 17, 935693, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='hey.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
